prod-agent: &prod-agent
  agents:
    queue: "groupapps-prod:cicd"

steps:
  - block: "Request Deploy to Production"
    branches: "master"

  - label: ":rocket: Deploy to Production"
    commands: "service/deploy.sh salesforce-data-masking"
    branches: "master"
    plugins:
      artifacts#v1.2.0:
        upload: "service/node_modules"

      docker:
        image: node:12-slim
        always-pull: true
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/usr/bin/docker:/usr/bin/docker"
        environment:
          - BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER
          - ENVIRONMENT=prod
          - AWS_DEFAULT_REGION=ap-southeast-2
    <<: *prod-agent
